
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec  9 2025 14:59:31 IST (Dec  9 2025 09:29:31 UTC)

// Verification Directory fv/fa 

module fa(a, b, c, s, cy);
  input a, b, c;
  output s, cy;
  wire a, b, c;
  wire s, cy;
  ADDFXL g87__2398(.A (a), .B (b), .CI (c), .CO (cy), .S (s));
endmodule

