
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec  9 2025 11:48:16 IST (Dec  9 2025 06:18:16 UTC)

// Verification Directory fv/rca_rd 
`timescale 1ns/10ps
module rca_rd(a, b, cin, s, ca);
  input [3:0] a, b;
  input cin;
  output [3:0] s;
  output ca;
  wire [3:0] a, b;
  wire cin;
  wire [3:0] s;
  wire ca;
  wire n_0, n_2, n_4;
  ADDFXL g282__2398(.A (a[3]), .B (b[3]), .CI (n_4), .CO (ca), .S
       (s[3]));
  ADDFX1 g283__5107(.A (b[2]), .B (a[2]), .CI (n_2), .CO (n_4), .S
       (s[2]));
  ADDFX1 g284__6260(.A (b[1]), .B (a[1]), .CI (n_0), .CO (n_2), .S
       (s[1]));
  ADDFX1 g285__4319(.A (b[0]), .B (a[0]), .CI (cin), .CO (n_0), .S
       (s[0]));
endmodule

